name: Dev - Deploy Static Website Files

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  WEB_BUCKET_NAME: dev.web.cuest.io
  WEB_CLOUDFRONT_DISTRIBUTION_ID:
  CONSOLE_BUCKET_NAME: dev.console.cuest.io
  CONSOLE_CLOUDFRONT_DISTRIBUTION_ID:
  NODE_VERSION: "18.15"
# Permission to work with AWS IAM role   
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  CD:
    name: Deployment
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set Node.js  ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run npm install
        run: npm ci

      - name: Build npm
        run: CI=false npm run build:dev

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy WEB
        run: |
              aws s3 sync ./build/html s3://${{ env.WEB_BUCKET_NAME }} --delete
              # --delete: Deletes files in the destination S3 bucket that don't exist in the local directory, ensuring a clean deployment
              aws cloudfront create-invalidation --distribution-id ${{ env.WEB_CLOUDFRONT_DISTRIBUTION_ID }}  --paths "/*" 

      - name: Deploy Dashboard 
        run: |
              aws s3 sync ./build/react s3://${{ env.CONSOLE_BUCKET_NAME }} --delete
              aws cloudfront create-invalidation --distribution-id ${{ env.CONSOLE_CLOUDFRONT_DISTRIBUTION_ID }}  --paths "/*" 


      # - name: Deployment Failed - Send Slack message in case of failure
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.15.0
      #   with:
      #     channel-id: "###########"
      #     slack-message: |
      #       Hello @here !
      #       :no_entry:  Deployment for service *${{ github.repository }}* failed  :no_entry:
      #       *Please review the logs of the failed deployment*
      #       repo: ${{ github.repository }}
      #       branch: ${{ github.ref }}
      #       author: *${{ github.event.head_commit.author.name }}*
      #       commit desc: "'${{ github.event.head_commit.message }}'' --> '${{ github.event.head_commit.url }}''"
      #       gitflow action: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # - name: Send Slack message (deployment-notification) on new deployment
      #   if: success()
      #   uses: slackapi/slack-github-action@v1.15.0
      #   with:
      #     channel-id: "########"
      #     slack-message: |
      #       Hello @here !
      #       :fire: New Deployment for service *${{ github.repository }}* :fire:
      #       repo: *${{ github.repository }}*
      #       branch: ${{ github.ref }}
      #       author: *${{ github.event.head_commit.author.name }}*
      #       commit desc: "'${{ github.event.head_commit.message }}'' --> '${{ github.event.head_commit.url }}''"
