name: Dev CI/CD

on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [mini-dev-deployment]  
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  # WEB_BUCKET_NAME: ${{ github.event.client_payload.actor }}.dev.web.cuest.io || dev.web.cuest.io
  WEB_BUCKET_NAME: 'dev.web.cuest.io'
  CONSOLE_BUCKET_NAME: 'dev.console.cuest.io' 
  # CONSOLE_BUCKET_NAME: ${{ github.event.client_payload.actor }}.dev.console.cuest.io' || 'dev.console.cuest.io' 
  NODE_VERSION: "18.15"
# Permission to work with AWS IAM role   
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  CD:
    name: Deployment
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CUEST_DEV_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Set Node.js  ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run npm install
        run: npm ci

      - name: Build npm
        run: CI=false npm run build:dev

      - name: Deploy WEB
        run: |
              aws s3 sync ./build/html s3://${{ env.WEB_BUCKET_NAME }} --delete
              # --delete: Deletes files in the destination S3 bucket that don't exist in the local directory, ensuring a clean deployment

      - name: Deploy Dashboard 
        run: |
              aws s3 sync ./build/react s3://${{ env.CONSOLE_BUCKET_NAME }} --delete
