name: PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches: ["ci_cd/main"]

env:
  NODE_VERSION: "16.14"

jobs:
  CI:
    name: Build
    if: (github.event.pull_request.merged != true && github.event.action != 'closed')
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.14
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build
