name: Prod Deploy

on:
  repository_dispatch:
    types: [prod-deployment]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  WEB_BUCKET_NAME: prod.cuest.io
  CONSOLE_BUCKET_NAME: console.prod.cuest.io
  NODE_VERSION: "18.15"
# Permission to work with AWS IAM role   
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  CD:
    name: Deployment
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_CUEST_PROD_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Set Node.js  ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run npm install
        run: npm ci

      - name: update aws-export.js
        if: ${{ ! github.event.client_payload.actor }}
        run: |
          sed -ie "s/<pool-id>/us-east-1_C7xZd3JlF/" src/aws-exports.js
          sed -ie "s/<app-client-id>/6k7kfknd1l4lng64p6l89c8o8c/" src/aws-exports.js

          cat src/aws-exports.js
      
      - name: Build npm
        run: CI=false npm run build:prod



      - name: Deploy WEB
        run: |
              aws s3 cp s3://${{ env.WEB_BUCKET_NAME }} s3://backup-${{ env.WEB_BUCKET_NAME }}
              aws s3 sync ./build/html s3://${{ env.WEB_BUCKET_NAME }} --delete

      - name: Deploy Dashboard 
        run: |
              aws s3 cp s3://${{ env.CONSOLE_BUCKET_NAME }} s3://backup-${{ env.CONSOLE_BUCKET_NAME }}
              aws s3 sync ./build/react s3://${{ env.CONSOLE_BUCKET_NAME }} --delete

              
      # - name: Deployment Failed - Send Slack message in case of failure
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.15.0
      #   with:
      #     channel-id: "###########"
      #     slack-message: |
      #       Hello @here !
      #       :no_entry:  Deployment for service *${{ github.repository }}* failed  :no_entry:
      #       *Please review the logs of the failed deployment*
      #       repo: ${{ github.repository }}
      #       branch: ${{ github.ref }}
      #       author: *${{ github.event.head_commit.author.name }}*
      #       commit desc: "'${{ github.event.head_commit.message }}'' --> '${{ github.event.head_commit.url }}''"
      #       gitflow action: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # - name: Send Slack message (deployment-notification) on new deployment
      #   if: success()
      #   uses: slackapi/slack-github-action@v1.15.0
      #   with:
      #     channel-id: "########"
      #     slack-message: |
      #       Hello @here !
      #       :fire: New Deployment for service *${{ github.repository }}* :fire:
      #       repo: *${{ github.repository }}*
      #       branch: ${{ github.ref }}
      #       author: *${{ github.event.head_commit.author.name }}*
      #       commit desc: "'${{ github.event.head_commit.message }}'' --> '${{ github.event.head_commit.url }}''"
