name: Prod Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  WEB_BUCKET_NAME: prod.cuest.io
  CONSOLE_BUCKET_NAME: console.prod.cuest.io
  NODE_VERSION: "18.15"
# Permission to work with AWS IAM role   
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  CD:
    name: Deployment
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_CUEST_PROD_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Set Node.js  ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run npm install
        run: npm ci

      - name: update aws-export.js
        run: |
          sed -ie "s/<pool-id>/us-east-1_C7xZd3JlF/" src/aws-exports.js
          sed -ie "s/<app-client-id>/6k7kfknd1l4lng64p6l89c8o8c/" src/aws-exports.js
          cat src/aws-exports.js
      
      - name: Build npm
        run: CI=false npm run build:prod

      - name: Deploy WEB
        run: |
              aws s3 cp s3://${{ env.WEB_BUCKET_NAME }} s3://backup-${{ env.WEB_BUCKET_NAME }}
              aws s3 sync ./build/html s3://${{ env.WEB_BUCKET_NAME }} --delete

      - name: Deploy Dashboard 
        run: |
              aws s3 cp s3://${{ env.CONSOLE_BUCKET_NAME }} s3://backup-${{ env.CONSOLE_BUCKET_NAME }}
              aws s3 sync ./build/react s3://${{ env.CONSOLE_BUCKET_NAME }} --delete
